// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'awesome': string;
  'bad': string;
  'good': string;
  'score__inner': string;
  'score__rating': string;
  'score__result-message': string;
}
export const cssExports: CssExports;
export default cssExports;
