// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'btn': string;
  'finish-btn': string;
  'start-btn': string;
}
export const cssExports: CssExports;
export default cssExports;
