// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'form': string;
  'form__btn': string;
  'form__btn-inner': string;
  'form__field': string;
  'form__field-inner': string;
}
export const cssExports: CssExports;
export default cssExports;
