// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'answer': string;
  'answer__question': string;
  'answer_correct-answer': string;
  'answer_user-answer': string;
  'answers': string;
  'answers__header': string;
  'answers__inner': string;
}
export const cssExports: CssExports;
export default cssExports;
