// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'quiz__body': string;
  'quiz__score': string;
}
export const cssExports: CssExports;
export default cssExports;
