// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'app__header': string;
  'app__next-btn': string;
  'app__score': string;
  'app__start-button': string;
}
export const cssExports: CssExports;
export default cssExports;
