// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'app': string;
  'app__buttons': string;
  'app__header': string;
  'app__score': string;
}
export const cssExports: CssExports;
export default cssExports;
