// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  card: string;
  "card__answer-btn": string;
  "card__answer-btn-inner": string;
  "card__answer-btns-container": string;
  "card__correct-answer": string;
  card__question: string;
  "card__question-number": string;
  "card__wrong-answer": string;
}
export const cssExports: CssExports;
export default cssExports;
